CREATE TABLE MEDICINE(
MEDICINE_ID VARCHAR(50) NOT NULL,
NAME TEXT,
DESCRIPTION TEXT,
PRICE DOUBLE,
LICENSE VARCHAR(50),
CIRCULATION BOOLEAN,
QUANTITY INT,
PRIMARY KEY(MEDICINE_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

SHOW TABLES;

CREATE TABLE EFFECT(
EFFECT_ID VARCHAR(50) NOT NULL,
DESCRIPTION TEXT,
PRIMARY KEY(EFFECT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PRODUCER(
PRODUCER_ID VARCHAR(50) NOT NULL,
NAME TEXT,
DESCRIPTION TEXT,
TEL VARCHAR(20),
ADDRESS TEXT,
PRIMARY KEY(PRODUCER_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE MEDICINE_PRODUCER(
MEDICINE_ID VARCHAR(50) NOT NULL,
PRODUCER_ID VARCHAR(50) NOT NULL,
PRIMARY KEY (MEDICINE_ID,PRODUCER_ID),
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID),
FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCER(PRODUCER_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE MEDICINE_EFFECT(
MEDICINE_ID VARCHAR(50) NOT NULL,
EFFECT_ID VARCHAR(50) NOT NULL,
PRIMARY KEY (MEDICINE_ID,EFFECT_ID),
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID),
FOREIGN KEY (EFFECT_ID) REFERENCES EFFECT(EFFECT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE ACTIVE_SUBSTANCE(
ACTIVE_SUBSTANCE_ID VARCHAR(50) NOT NULL,
NAME TEXT,
DESCRIPTION TEXT,
PRIMARY KEY(ACTIVE_SUBSTANCE_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE MEDICINE_ACTIVE_SUBSTANCE(
MEDICINE_ID VARCHAR(50) NOT NULL,
ACTIVE_SUBSTANCE_ID VARCHAR(50) NOT NULL,
PRIMARY KEY (MEDICINE_ID,ACTIVE_SUBSTANCE_ID),
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID),
FOREIGN KEY (ACTIVE_SUBSTANCE_ID) REFERENCES ACTIVE_SUBSTANCE(ACTIVE_SUBSTANCE_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE SIDE_EFFECT(
SIDE_EFFECT_ID VARCHAR(50) NOT NULL,
DESCRIPTION TEXT,
PRIMARY KEY (SIDE_EFFECT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE MEDICINE_SIDE_EFFECT(
MEDICINE_ID VARCHAR(50) NOT NULL,
SIDE_EFFECT_ID VARCHAR(50) NOT NULL,
PRIMARY KEY (MEDICINE_ID,SIDE_EFFECT_ID),
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID),
FOREIGN KEY (SIDE_EFFECT_ID) REFERENCES SIDE_EFFECT(SIDE_EFFECT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE DOCTOR(
DOCTOR_ID VARCHAR(50) NOT NULL,
NAME TEXT,
CATEGORY TEXT,
TEL VARCHAR(20),
EMAIL TEXT,
ADDRESS TEXT,
PRIMARY KEY (DOCTOR_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PATIENT(
PATIENT_ID VARCHAR(50) NOT NULL,
NAME TEXT,
AGE DATE,
TEL VARCHAR(20),
EMAIL TEXT,
ADDRESS TEXT,
PRIMARY KEY(PATIENT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE DOCTOR_PATIENT(
DOCTOR_ID VARCHAR(50) NOT NULL,
PATIENT_ID VARCHAR(50) NOT NULL,
PRIMARY KEY (DOCTOR_ID, PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PRESCRIPTION(
PRESCRIPTION_ID VARCHAR(50) NOT NULL,
DOCTOR_ID VARCHAR(50) NOT NULL,
PATIENT_ID VARCHAR(50) NOT NULL,
DATE DATE,
DESCRIPTION TEXT,
PRIMARY KEY(PRESCRIPTION_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE MEDICINE_PRESCRIPTION(
MEDICINE_ID VARCHAR(50) NOT NULL,
PRESCRIPTION_ID VARCHAR(50) NOT NULL,
MEDICINE_DESCRIPTION_QUANTITY INT,
PRIMARY KEY (MEDICINE_ID, PRESCRIPTION_ID),
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID),
FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;


